# Quality Control


**Loading packages**

```{r, echo=TRUE, results="hide", warning=FALSE, message=FALSE}
library(XMAS2)
library(dplyr)
library(tibble)
library(phyloseq)
```

The taxonomic levels of spike-in sample's bacteria is species. Firstly, using the `summarize_taxa` to get the genus level phyloseq object and then do `run_RefCheck` under the optimal parameters.

## spike-in sample (BRS)

* get the BRS_ID
```{r, warning=FALSE, message=FALSE}
metaphlan2_ps_LOD_species <- aggregate_LOD_taxa(ps = metaphlan2_ps, 
                                                taxa_level = "Species", 
                                                cutoff = 1e-04)
metaphlan2_ps_LOD_species@sam_data
```

* run `run_RefCheck`
```markdown
run_RefCheck(
    ps = metaphlan2_ps_LOD_species,
    BRS_ID = "refE",
    Ref_type = "MGS")
```


```{r, warning=FALSE, message=TRUE, collapse=TRUE, echo=FALSE}
run_RefCheck(
    ps = metaphlan2_ps_LOD_species,
    BRS_ID = "refE",
    Reference = NULL,
    Ref_type = "MGS",
    Save = NULL)
```

## Spike-in sample's (BRS) remove
```{r, warning=FALSE, message=FALSE}
metaphlan2_ps_LOD_species_remove_BRS <- get_GroupPhyloseq(
                                           ps = metaphlan2_ps_LOD_species,
                                           group = "Group",
                                           group_names = "QC",
                                           discard = TRUE)
metaphlan2_ps_LOD_species_remove_BRS
```


## Systematic Information
```{r}
devtools::session_info()
```