# Diversity analysis

**Loading packages**

```{r, echo=TRUE, results="hide", warning=FALSE, message=FALSE}
library(XMAS2)
library(dplyr)
library(tibble)
library(phyloseq)
library(ggplot2)
library(ggpubr)
```

## Alpha diveristy

* Calculate the alpha diversity 

**Notes:** choosing the measures (*Shannon, Simpson and InvSimpson*) only for relative abundance. 
```{r, warning=FALSE, message=FALSE}
metaphlan2_ps_species_alpha <- run_alpha_diversity(ps=metaphlan2_ps_species, measures = c("Shannon", "Simpson", "InvSimpson"))
DT::datatable(metaphlan2_ps_species_alpha)
```

* visualization
```{r, warning=FALSE, message=FALSE, fig.width=6, fig.height=4, fig.align="center", fig.cap="Alpha diversity"}
plot_boxplot(data=metaphlan2_ps_species_alpha,
             y_index = c("Shannon", "Simpson", "InvSimpson"),
             group = "Group",
             group_names = c("AA", "BB"),
             group_color = c("red", "blue"),
             do_test = TRUE,
             method = "wilcox.test")
```


## Beta diversity

* beta dipersion
```{r, warning=FALSE, message=FALSE, fig.width=5, fig.height=4, fig.align="center", fig.cap="Beta diversity"}
metaphlan2_ps_beta <- run_beta_diversity(ps=metaphlan2_ps_species, method = "bray", group = "Group")
metaphlan2_ps_beta$BetaDispersion
```


## Systematic Information
```{r}
devtools::session_info()
```