# PERMANOVA + beta dispersion + Ordination

**Loading packages**

```{r, echo=TRUE, results="hide", warning=FALSE, message=FALSE}
library(XMAS2)
library(dplyr)
library(tibble)
library(phyloseq)
library(ggplot2)
library(ggpubr)
```


## PERMANOVA
```{r, warning=FALSE, message=FALSE}
metaphlan2_ps_LOD_species_per <- run_permanova(ps = metaphlan2_ps_LOD_species, 
                                               method = "bray", 
                                               columns = "Group")
print(metaphlan2_ps_LOD_species_per)
```

The PERMANOVA result of the Group (AdjustedPvalue > 0.05) revealed that the two groups had not the distinct patterns of microbial community.

## beta dispersion 
```{r}
beta_df <- run_beta_diversity(ps = metaphlan2_ps_LOD_species, 
                              method = "bray", 
                              group = "Group")
```


## Ordination

We performed ordination by using Principal Coordinate Analysis (PCoA).
```{r, warning=FALSE, message=FALSE, fig.width=9, fig.height=6, fig.align="center", fig.cap="PCoA"}
metaphlan2_ps_species_ordination <- run_ordination(
                                       ps = metaphlan2_ps_LOD_species,
                                       group = "Group",
                                       method = "PCoA")

# plot_Ordination(ResultList = metaphlan2_ps_species_ordination, 
#                 group = "Group", 
#                 group_names = c("AA", "BB"),
#                 group_color = c("blue", "red"),
#                 circle_type = "ellipse_groups",
#                 sidelinechart = FALSE,
#                 sideboxplot = TRUE)

plot_Ordination(ResultList = metaphlan2_ps_species_ordination, 
                group = "Group", 
                group_names = c("AA", "BB"),
                group_color = c("blue", "red"))
```


## Systematic Information
```{r}
devtools::session_info()
```
