# Test Example


## Loading packages
```{r, echo=TRUE, results="hide", warning=FALSE, message=FALSE}
library(XMAS2)
library(dplyr)
library(tibble)
library(phyloseq)
library(ggplot2)
library(ggpubr)
library(readxl)
```


## Loading data 
```{r, warning=FALSE, message=FALSE}
metaphlan2_res <- read.table("DataSet/RawData/merged_metaphlan2.tsv",
                             header = TRUE, stringsAsFactors = FALSE) %>%
  tibble::rownames_to_column("ID")

metadata <- read_xlsx("DataSet/RawData/诺禾宏基因组678月-ZH.xlsx", sheet = 3)
```


## Step1: Convert inputs into phyloseq data
```{r, warning=FALSE, message=FALSE}
metaphlan2_res_list <- import_metaphlan_taxa(metaphlan2_res, taxa_level = "Species")
tax_tab <- metaphlan2_res_list$tax_tab

otu_tab <- metaphlan2_res_list$abu_tab
colnames(otu_tab) <- gsub("X", "S_", colnames(otu_tab))

sam_tab <- metadata %>% data.frame() %>%
  dplyr::mutate(Group=ifelse(SampleType == "粪便", "Stool", 
                             ifelse(SampleType == "QC", "QC", "Product"))) %>%
  dplyr::select(SampleTubeID, Group, everything())
rownames(sam_tab) <- paste0("S_", sam_tab$SeqID_MGS)

overlap_samples <- intersect(rownames(sam_tab), colnames(otu_tab))

otu_tab_cln <- otu_tab[, match(overlap_samples, colnames(otu_tab))]
sam_tab_cln <- sam_tab[match(overlap_samples, rownames(sam_tab)), ]
rownames(sam_tab_cln) <- overlap_samples

metaphlan2_ps <- get_metaphlan_phyloseq(otu_tab = otu_tab_cln, 
                                   sam_tab = sam_tab_cln,
                                   tax_tab = tax_tab)
metaphlan2_ps

if (!dir.exists("DataSet/Step1/")) {
  dir.create("DataSet/Step1/")
}
saveRDS(metaphlan2_ps, "DataSet/Step1/Donor_MGS_phyloseq.RDS", compress = TRUE)
```


Transform limit of detection (LOD) into Zeros
```{r, warning=FALSE, message=FALSE}
if (0) {
# species
metaphlan2_ps_species_LOD <- aggregate_LOD_taxa(metaphlan2_ps, 
                                                taxa_level = "Species", 
                                                cutoff = 1e-04)

# genus
metaphlan2_ps_genus_LOD <- aggregate_LOD_taxa(metaphlan2_ps, 
                                                taxa_level = "Genus", 
                                                cutoff = 1e-04)

# order
metaphlan2_ps_order_LOD <- aggregate_LOD_taxa(metaphlan2_ps, 
                                                taxa_level = "Order", 
                                                cutoff = 1e-04)

if (!dir.exists("DataSet/Step2/")) {
  dir.create("DataSet/Step2/")
}
saveRDS(metaphlan2_ps_species_LOD, "DataSet/Step2/Donor_MGS_phyloseq_species_LOD.RDS", compress = TRUE)
saveRDS(metaphlan2_ps_genus_LOD, "DataSet/Step2/Donor_MGS_phyloseq_genus_LOD.RDS", compress = TRUE)
saveRDS(metaphlan2_ps_order_LOD, "DataSet/Step2/Donor_MGS_phyloseq_order_LOD.RDS", compress = TRUE)  
}
```


## Step2: BRS checking
```{r, warning=FALSE, message=FALSE}
metaphlan2_ps <- readRDS("DataSet/Step1/Donor_MGS_phyloseq.RDS")
metaphlan2_ps_species <- summarize_taxa(metaphlan2_ps, taxa_level = "Species")
tail(metaphlan2_ps_species@sam_data %>% data.frame())

run_RefCheck(
    ps=metaphlan2_ps_species,
    BRS_ID="S_7222",
    Reference=NULL,
    Ref_type="MGS",
    Save=NULL)

metaphlan2_ps_remove_BRS <- get_GroupPhyloseq(
                     ps = metaphlan2_ps,
                     group = "Group",
                     group_names = "QC",
                     discard = TRUE)
metaphlan2_ps_remove_BRS

if (!dir.exists("DataSet/Step3/")) {
  dir.create("DataSet/Step3/")
}
saveRDS(metaphlan2_ps_remove_BRS, "DataSet/Step3/Donor_MGS_phyloseq_remove_BRS.RDS", compress = TRUE)
```


## Step3: Extracting specific taxonomic level
```{r, warning=FALSE, message=FALSE}
metaphlan2_ps_remove_BRS <- readRDS("DataSet/Step3/Donor_MGS_phyloseq_remove_BRS.RDS")

metaphlan2_ps_remove_BRS_species <- summarize_taxa(metaphlan2_ps_remove_BRS, 
                                                taxa_level = "Species")
metaphlan2_ps_remove_BRS_species

metaphlan2_ps_remove_BRS_genus <- summarize_taxa(metaphlan2_ps_remove_BRS, 
                                                taxa_level = "Genus")
metaphlan2_ps_remove_BRS_genus


if (!dir.exists("DataSet/Step4/")) {
  dir.create("DataSet/Step4/")
}
saveRDS(metaphlan2_ps_remove_BRS_species, "DataSet/Step4/Donor_MGS_phyloseq_remove_BRS_species.RDS", compress = TRUE)
saveRDS(metaphlan2_ps_remove_BRS_genus, "DataSet/Step4/Donor_MGS_phyloseq_remove_BRS_genus.RDS", compress = TRUE)
```


## Step4: GlobalView
```{r, warning=FALSE, message=FALSE, fig.align="center", fig.width=8, fig.height=5, fig.cap="diversity and ordination and composition(Example)"}
metaphlan2_ps_remove_BRS_species <- readRDS("DataSet/Step4/Donor_MGS_phyloseq_remove_BRS_species.RDS")

# alpha
metaphlan2_ps_remove_BRS_species_alpha <- run_alpha_diversity(ps=metaphlan2_ps_remove_BRS_species, 
                                                measures = c("Shannon", "Simpson", "InvSimpson"))
plot_boxplot(data=metaphlan2_ps_remove_BRS_species_alpha,
             y_index = c("Shannon", "Simpson", "InvSimpson"),
             group = "Group",
             group_names = c("Stool", "Product"),
             group_color = c("red", "blue"))

# beta
metaphlan2_ps_remove_BRS_species_beta <- run_beta_diversity(ps=metaphlan2_ps_remove_BRS_species, method = "bray")
plot_distance_corrplot(metaphlan2_ps_remove_BRS_species_beta$BetaDistance)

# permanova
run_permanova(ps=metaphlan2_ps_remove_BRS_species, method = "bray", columns = "Group")

# beta dispersion
beta_df <- run_beta_diversity(ps=metaphlan2_ps_remove_BRS_species, method = "bray", group = "Group")

# ordination
metaphlan2_ps_ordination <- run_ordination(
                       ps = metaphlan2_ps_remove_BRS_species,
                       group = "Group",
                       method = "PCoA")

plot_Ordination(ResultList = metaphlan2_ps_ordination, 
                group = "Group", 
                group_names = c("Stool", "Product"),
                group_color = c("blue", "red"))

# Microbial composition
plot_stacked_bar_XIVZ(
        phyloseq = metaphlan2_ps_remove_BRS_species,
        level = "Phylum",
        feature = "Group")
```

## Step6: Differential Analysis
```{r, warning=FALSE, message=FALSE, fig.align="center", fig.width=8, fig.height=5, fig.cap="Differential Analysis (Example)"}
metaphlan2_ps_remove_BRS_species <- readRDS("DataSet/Step4/Donor_MGS_phyloseq_remove_BRS_species.RDS")

# filter & trim
metaphlan2_ps_remove_BRS_species_filter <- run_filter(metaphlan2_ps_remove_BRS_species, cutoff = 1e-4, unclass = TRUE)
metaphlan2_ps_remove_BRS_species_filter_trim <- run_trim(metaphlan2_ps_remove_BRS_species_filter, cutoff = 0.1, trim = "feature")
metaphlan2_ps_remove_BRS_species_filter_trim

# lefse
metaphlan2_ps_lefse <- run_lefse(
                    metaphlan2_ps_remove_BRS_species_filter_trim,
                    group = "Group",
                    group_names = c("Stool", "Product"),
                    Lda = 2)
# # don't run this code when you do lefse in reality
# metaphlan2_ps_lefse$LDA_Score <- metaphlan2_ps_lefse$LDA_Score * 1000
plot_lefse(
  da_res = metaphlan2_ps_lefse,
  x_index = "LDA_Score",
  x_index_cutoff = 2,
  group_color = c("green", "red"))


metaphlan2_ps_wilcox <- run_wilcox(
                    metaphlan2_ps_remove_BRS_species_filter_trim,
                    group = "Group",
                    group_names = c("Stool", "Product"))
plot_volcano(
    metaphlan2_ps_wilcox,
    group_names = c("Stool", "Product"),
    x_index = "Log2FoldChange (Rank)\nStool_vs_Product",
    x_index_cutoff = 0.5,
    y_index = "Pvalue",
    y_index_cutoff = 0.05,
    group_color = c("red", "grey", "blue"),
    topN = 5)

if (!dir.exists("DataSet/Step8/")) {
  dir.create("DataSet/Step8/")
}
saveRDS(metaphlan2_ps_remove_BRS_species_filter_trim, "DataSet/Step6/Donor_MGS_phyloseq_remove_BRS_species_filter_trim.RDS", compress = TRUE)
```


## Systematic Information
```{r}
sessionInfo()
```
